# Generated by Django 3.2 on 2024-05-04 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('counter_id', models.IntegerField(default=None)),
                ('cashier_name', models.TextField(default=None)),
                ('customer_name', models.TextField(default=None)),
                ('date', models.DateField(default=None)),
                ('totel', models.IntegerField(default=None)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.branch')),
            ],
        ),
    ]
