# Generated by Django 3.2 on 2024-05-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='cashier_name',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='customer_name',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
