# Generated by Django 3.2 on 2024-05-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240504_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='items',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
