# Generated by Django 3.2 on 2024-05-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_voucher_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='totel',
            new_name='total',
        ),
    ]
